#include "PhpIniRepair.h"

#include <QDir>
#include <QDirIterator>
#include <QFileInfo>
#include <QJsonArray>
#include <QProcess>
#include <QSaveFile>

namespace {

void appendLog(QStringList *logLines, const QString &line)
{
    if (logLines) {
        logLines->append(line);
    }
}

QString installedExtensionPath(const QString &installPath, const QString &fileName)
{
    const QString extensionRoot = QDir(installPath).filePath(QStringLiteral("lib/php/extensions"));
    QDirIterator iterator(extensionRoot, {fileName}, QDir::Files, QDirIterator::Subdirectories);
    if (iterator.hasNext()) {
        return iterator.next();
    }
    return {};
}

bool phpReportsModule(const QString &installPath, const QStringList &moduleNames)
{
    QProcess process;
    process.setProgram(QDir(installPath).filePath(QStringLiteral("bin/php")));
    process.setArguments({QStringLiteral("-n"), QStringLiteral("-m")});
    process.start();
    if (!process.waitForStarted(5000) || !process.waitForFinished(10000)) {
        return false;
    }
    if (process.exitStatus() != QProcess::NormalExit || process.exitCode() != 0) {
        return false;
    }

    const QString output = QString::fromLocal8Bit(process.readAllStandardOutput())
        + QString::fromLocal8Bit(process.readAllStandardError());
    const QStringList lines = output.split(QLatin1Char('\n'), Qt::SkipEmptyParts);
    for (const QString &line : lines) {
        const QString trimmed = line.trimmed();
        for (const QString &moduleName : moduleNames) {
            if (trimmed.compare(moduleName, Qt::CaseInsensitive) == 0) {
                return true;
            }
        }
    }
    return false;
}

} // namespace

bool PhpIniRepair::ensureForManifest(const QJsonObject &manifest, QStringList *logLines)
{
    const QString installPath = manifest.value(QStringLiteral("installPath")).toString();
    if (installPath.isEmpty()) {
        return false;
    }

    const QString phpIniPath = manifest.value(QStringLiteral("phpIniPath")).toString(
        QDir(installPath).filePath(QStringLiteral("lib/php.ini")));
    if (QFileInfo::exists(phpIniPath)) {
        return true;
    }

    QStringList lines;
    lines << QStringLiteral("; Generated by LangManager.")
          << QStringLiteral("memory_limit=512M")
          << QStringLiteral("date.timezone=UTC");

    const QJsonArray modules = manifest.value(QStringLiteral("selectedModules")).toArray();
    bool needsOpcache = false;
    for (const QJsonValue &value : modules) {
        if (value.toString() == QStringLiteral("OPcache")) {
            needsOpcache = true;
            break;
        }
    }

    if (needsOpcache) {
        const QString opcachePath = installedExtensionPath(installPath, QStringLiteral("opcache.so"));
        const bool hasBuiltInOpcache = opcachePath.isEmpty()
            && phpReportsModule(installPath, {QStringLiteral("Zend OPcache"), QStringLiteral("OPcache")});
        if (opcachePath.isEmpty() && !hasBuiltInOpcache) {
            appendLog(logLines, QStringLiteral("Cannot repair php.ini: opcache.so is missing for %1").arg(installPath));
            return false;
        }
        lines << QString()
              << QStringLiteral("[opcache]");
        if (opcachePath.isEmpty()) {
            appendLog(logLines, QStringLiteral("OPcache is built into PHP; repaired php.ini will not add zend_extension=opcache.so."));
        } else {
            lines << QStringLiteral("zend_extension=%1").arg(opcachePath);
        }
        lines << QStringLiteral("opcache.enable=1")
              << QStringLiteral("opcache.enable_cli=1")
              << QStringLiteral("opcache.memory_consumption=128")
              << QStringLiteral("opcache.interned_strings_buffer=16")
              << QStringLiteral("opcache.max_accelerated_files=20000")
              << QStringLiteral("opcache.validate_timestamps=1")
              << QStringLiteral("opcache.revalidate_freq=0");
    }

    const QJsonArray peclExtensions = manifest.value(QStringLiteral("peclExtensions")).toArray();
    if (!peclExtensions.isEmpty()) {
        lines << QString() << QStringLiteral("[langmanager-pecl]");
        for (const QJsonValue &value : peclExtensions) {
            const QString extension = value.toString();
            const QString extensionPath = installedExtensionPath(installPath, QStringLiteral("%1.so").arg(extension));
            if (extensionPath.isEmpty()) {
                appendLog(logLines, QStringLiteral("Cannot repair php.ini: %1.so is missing for %2").arg(extension, installPath));
                return false;
            }
            if (extension == QStringLiteral("xdebug")) {
                lines << QStringLiteral("zend_extension=%1").arg(extensionPath);
            } else {
                lines << QStringLiteral("extension=%1").arg(extensionPath);
            }
        }
    }

    QDir().mkpath(QFileInfo(phpIniPath).absolutePath());
    QSaveFile phpIniFile(phpIniPath);
    if (!phpIniFile.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        appendLog(logLines, QStringLiteral("Cannot repair php.ini %1: %2").arg(phpIniPath, phpIniFile.errorString()));
        return false;
    }
    phpIniFile.write(lines.join(QStringLiteral("\n")).toUtf8());
    phpIniFile.write("\n");
    if (!phpIniFile.commit()) {
        appendLog(logLines, QStringLiteral("Cannot commit repaired php.ini %1: %2").arg(phpIniPath, phpIniFile.errorString()));
        return false;
    }

    appendLog(logLines, QStringLiteral("Repaired missing php.ini: %1").arg(phpIniPath));
    return true;
}
